edge:
  0: [1, 5, 6]
  # Edge 1 is assigned by random
  2: [2, 7, 9]

rounds:
  0:
    edges:
      0: [1, 6]
      1: [3, 4]
      2: [2]
  1:
    edges:
      0: [1, 6]
      # edge 1 is selected by random
      2: [2]
  # round 2 and onwards is selected by random
