default:
  n_samples: 100
  dist: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

client_1:
  n_samples: 100
  dist: [0, 0.6, 0, 0, 0, 0.4, 0, 0, 0, 0]

client_4:
  n_samples: 100
  dist: [0.7, 0, 0.3, 0, 0, 0, 0, 0, 0, 0]
